### ISSUE TITLE
Design the Documentation page where the user gets to access the library, read the documentation in high fidelity

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#14]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by OluwakemiOy** [comment]
Here are the links for the high fidelity design for the documentation page for the Authenticated users

Documentation page (Get started)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1775%3A10156

Documentation page (Introduction)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1775%3A10538

Documentation page (Animation)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2466%3A16504

**Comment by Oderindecaleb** [comment]
These are the links for the high fidelity design for the documentation page for the Unauthenticated users
Documentation page (Get started)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1952%3A11171
Documentation page (Introduction)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1952%3A11664
Documentation page (Animation)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2462%3A18085
