### ISSUE TITLE
Design the Documentation page where the user gets to access the library, read the documentation in low fidelity

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#15]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by OluwakemiOy** [comment]
These are the links for the documentation page design in low-fidelity

Documentation page (Introduction)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=866%3A5643

Documentation page (Examples)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=382%3A941

**Comment by Oderindecaleb** [comment]
Here are the links for the documentation page design in low fidelity 
Documentation page (Get Started)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=377%3A1018

Documentation page (Animations)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=382%3A1214
