### ISSUE TITLE
Brainstorm on ideas

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#16]
brainstorming has been concluded on figma board
https://www.figma.com/file/skC8RSnVpQveSzGzhOWY0I/research-and-brainstorming?node-id=0%3A1

**Comment by Victorasta1** [comment]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1463%3A11680

This is the link to the  Brainstorming frame on figma

**Comment by Fawazah** [comment]
This is the link to the brainstorming ideas - 
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2880%3A27332

This is the link to the idea matrix - 
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47674

**Comment by Awe80me** [comment]
I just reconfirmed the links to the Brainstorming Ideas and the Idea Matrix pages my colleagues posted.

**Comment by Mimi1510** [comment]
The links on Brainstorming ideas and idea matrix confirmed

**Comment by DavidIkechi** [comment]
Task completed! Confirmed!

**Comment by Victorasta1** [comment]
I Can confirm that this issue is completed
