### ISSUE TITLE
Design the About us page in low fidelity

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#18]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by Fawazah** [comment]
I believe we are completed this in the morning, moving to the hi-fi

**Comment by Awe80me** [comment]
This has been finalised.

[Lo-Fi / About Us Page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1268%3A9316)

Check it out with the attached link
