### ISSUE TITLE
Design the Website's Landing page. High fidelity version 

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#19]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by Fawazah** [comment]
We are almost done with this. It's just to add the remaining illustrations

**Comment by Awe80me** [comment]
This will be done before tomorrow

**Comment by Awe80me** [comment]
This is now finalised. Check attached links for references.

[Hi-Fi / Landing Page - Unauthenticated](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1171%3A7680)
[Hi-Fi / Landing Page - Authenticated](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=976%3A5150)

**Comment by flekkies** [comment]
Done

**Comment by flekkies** [comment]
Done
