### ISSUE TITLE
Design the Landing page in low fidelity

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#20]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by Fawazah** [comment]
This has been finalised

**Comment by Awe80me** [comment]
We're done with this

**Comment by flekkies** [comment]
Done

**Comment by flekkies** [comment]
Done
