### ISSUE TITLE
Design a Register/Log in page

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#21]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by OsawaruErica** [comment]
Design completed for Register page 
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=281%3A459

**Comment by OsawaruErica** [comment]
Design completed for Login page
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=781%3A4576

**Comment by OsawaruErica** [comment]
password recovery page completed
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1086%3A7373

**Comment by jcuchea** [comment]
Can confirm to conclusion of the Log in / Register page
