### ISSUE TITLE
Design a Register/Sign page in low fidelity

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#22]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by OsawaruErica** [comment]
##Link to completed lo-fi frame
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=781%3A4111

**Comment by OsawaruErica** [comment]
#Link to completed login lo-fi frame
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=781%3A4006

**Comment by jcuchea** [comment]
Necessary changes have been made. Link confrimed.
