### ISSUE TITLE
Design an high fidelity Support page for Users to contact us as regards problems or inquires not answered on the website 

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#23]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by DuoACe** [comment]
This is the figma link for Light mode support page for unauthenticated users
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2649%3A14459

**Comment by DuoACe** [comment]
Aliyat kindly drop the link to the Hifi light mode support page hifi authenticated user and close the issue

**Comment by Aliyatadeyanju** [comment]
Done

**Comment by Aliyatadeyanju** [comment]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2649%3A14458

This is the figma link for the Hifi Light mode support page for unauthenticated users

**Comment by Aliyatadeyanju** [comment]
All done

**Comment by Aliyatadeyanju** [comment]
Done
