### ISSUE TITLE
Design a low fidelity Support page

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#24]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by DuoACe** [comment]
Well done Aliyat, the lofi designs are in progress.
Remiaining just a few little touches

**Comment by DuoACe** [comment]
Aliyat you can go ahead and paste the figma link to our task here so that i can move the task from the in progress to done board

**Comment by Aliyatadeyanju** [comment]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1422%3A9704

This is the link to the lo-fi for the support page

**Comment by DuoACe** [comment]
Aliyat kindly close this issue, were done with it

**Comment by Aliyatadeyanju** [comment]
Alright

**Comment by DuoACe** [comment]
All is well and good on this page

**Comment by DuoACe** [comment]
This is the updated Figma Link to the low fidelity Support Page
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3367%3A19422
