### ISSUE TITLE
Create a Style guide consisting of Colour, Typography, Spacing, Alerts/notification, Buttons and input field.

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#25]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by Victorasta1** [comment]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1422%3A9700

Link to the actual frame showing the style guide

**Comment by Fawazah** [comment]
Below is the link to the style guide and components page - 
[Style guide and components](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1)

**Comment by Fawazah** [comment]
Below is the link to the style guide and components page -
[Style guide and components](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1)

**Comment by Awe80me** [comment]
Below is the link to the specific page of the Components and Style Guide that Awessome, Fawazah, and Victor worked on

[Components and Style Guides Page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1)

**Comment by OsawaruErica** [comment]
link to the input fields page
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=403%3A1927
