### ISSUE TITLE
Design the Wireframes and sketches (for all designers)

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#26]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by Fawazah** [comment]
Awesome and Fawazah worked on the wireframes for landing page and about us page

This is the link for the wireframe for landing page unauthenticated user - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25466

This is the link for the wireframe for landing page authenticated user - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25336

This is the link for the wireframe for about us page authenticated user - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25723

This is the link for the wireframe for about us page unauthenticated user - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25597

**Comment by Mimi1510** [comment]
The below is the link to the wireframe of the **Animation search page** I worked on:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A26110

**Comment by Awe80me** [comment]
"Awesome and Fawazah worked on the wireframes for landing page and about us page"

**Comment by Aliyatadeyanju** [comment]
Aliyat and Ayotomiwa worked on the wireframe for the support page

**Comment by Aliyatadeyanju** [comment]
Aliyat worked on the save changes successful wireframe, the link is below
https://www.figma.com/file/j1drbvRXQLsqEpHG3DfsbP/changes-successfully-saved-page?node-id=0%3A1

**Comment by DuoACe** [comment]
Ayotomiwa Ajewole worked on the wireframes for contact us page.
This is the link below
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3405%3A19426

**Comment by Oderindecaleb** [comment]
@Oderindecaleb  and @OluwakemiOy worked together to construct the wireframe for the documentation page

Documentation page 1 - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A24704
Documentation page 2 - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A24881
Documentation page 3 - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A24774

**Comment by HamzahOpemipo** [comment]
> Mimi1510, Hamzah and Victorasta1 worked on the wireframe of the user profile pages
> 
> [Wireframe / User profile pages](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2678%3A65859)

Updated link to User profile pages wireframe
[User Profile Pages Wireframe](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3625%3A19427)
