### ISSUE TITLE
Review and publish screener survey, interview and survey questions for user research

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#27]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1

This is the link to the figma board

**Comment by OsawaruErica** [comment]
Animo Research plan document to better understand the user
https://docs.google.com/document/d/139jnUvUZV3XcdpIgCxjvh4JVmwbO5p1NQdizOal7qf0/edit?usp=sharing

**Comment by Aliyatadeyanju** [comment]
I worked on the survey questions on the research plan document with Erica
https://docs.google.com/document/d/139jnUvUZV3XcdpIgCxjvh4JVmwbO5p1NQdizOal7qf0/edit?usp=sharing
