### ISSUE TITLE
Animation Library, Documentation page and text/content

### ISSUE THREAD

**Issue by Fawazah** [zuri-training/Team-100_AnimaLib#30]

**Comment by Kenechukwu2** [comment]
We have started researching and writing content for the Documentation page

**Comment by Victorasta1** [comment]
Fawazah is this for the Developers. Kindly indicate with a befitting Title

**Comment by Mabel007** [comment]
@Fawazah  @Kenechukwu2  @Victorasta1  @Rockranx  The documentation text or content https://docs.google.com/document/d/1jvLl1l80YFratAM04jDx-CjoE4dMAqBDRw7m1DICdjA/edit?usp=sharing

**Comment by Rockranx** [comment]
the slide snippet doesn't allow more than one animation to run at a time, the solutions that me and kene have come up with is to create multiple pages for each animation snippet.

**Comment by Mabel007** [comment]
https://github.com/zuri-training/Team-100_AnimaLib/commit/4c590965fafda9403263845f16970f1e7012ddc9


worked on the first, second and third page of the documentation page

**Comment by Kenechukwu2** [comment]
All done
