### ISSUE TITLE
ERD, UML, Code Schema, Views & URLs

### ISSUE THREAD

**Issue by Fawazah** [zuri-training/Team-100_AnimaLib#37]

**Comment by Tola-C** [comment]
The Entity Relationship Diagram for the Django models is completed, and the code layout and skeleton for the views and URL have also been mapped out in the document below:
https://docs.google.com/document/d/1d2eHTo1TvmEQp0yC8u-pkN3UIdEfriJ3KEZ_YBocQUA/edit?usp=sharing
