### ISSUE TITLE
Design several pages for User profile in low fidelity 

### ISSUE THREAD

**Issue by Victorasta1** [zuri-training/Team-100_AnimaLib#39]

**Comment by HamzahOpemipo** [comment]
User profile in low fidelity completed. See link attached below

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1492%3A11756

**Comment by HamzahOpemipo** [comment]
User profile in low fidelity completed. See link attached below

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2423%3A14678

**Comment by Mimi1510** [comment]
Below is the updated link for user profile pages in low fidelity:

[Lo-fi/ User profile pages - Authenticated](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2678%3A65859)

**Comment by Mimi1510** [comment]
HamzahOpemipo and Victorasta1, kindly confirm the above link
