### ISSUE TITLE
Design several pages for User profile in high fidelity 

### ISSUE THREAD

**Issue by Victorasta1** [zuri-training/Team-100_AnimaLib#40]

**Comment by HamzahOpemipo** [comment]
User profile high fidelity in progress

**Comment by HamzahOpemipo** [comment]
High fidelity user profile pages completed and its pending review. 
Link attached below.

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1492%3A12403

**Comment by HamzahOpemipo** [comment]
User Profile in high fidelity has been reviewed and handed over to the developers. See the attached links below

Light Mode : https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2425%3A14677
Dark Mode : https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2426%3A14679

**Comment by Mimi1510** [comment]
Thanks for dropping the links, Hamzah

**Comment by Mimi1510** [comment]
Below is the updated link for user profile in high fidelity page
[Hi -fi/ User profile pages - Authenticated user](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A29511)

**Comment by Mimi1510** [comment]
HamzahOpemipo and Victorasta1, kindly confirm the above link

**Comment by Victorasta1** [comment]
Mimi1510. The link you updated with is the link of the whole page and not the selected frame

**Comment by Victorasta1** [comment]
[Profile pages link](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3585%3A19426)
