### ISSUE TITLE
Design the page that will display error 404

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#43]

**Comment by flekkies** [comment]
On it

**Comment by flekkies** [comment]
Done with Error 404 page

**Comment by HamzahOpemipo** [comment]
Hi Flekkies, Please attach the link to the Error 404 page and close this issue. Thanks

**Comment by flekkies** [comment]
[https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1](url)

**Comment by flekkies** [comment]
Done

**Comment by flekkies** [comment]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A114528
