### ISSUE TITLE
Design the page that will display error 500

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#44]

**Comment by OsawaruErica** [comment]
As a developer, I want to understand error messages, so I know what to do next when an error page appears.
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1779%3A10885

**Comment by OsawaruErica** [comment]
As a developer, I want to understand error messages, so I know what to do next when an error page appears.(dark mode)
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2778%3A47594

**Comment by Mimi1510** [comment]
Hi Erica, kindly update your link
