### ISSUE TITLE
Design the page that will display "animation search not found"

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#45]

**Comment by Mimi1510** [comment]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2020%3A14388

**Comment by HamzahOpemipo** [comment]
Hi @Mimi1510, Nicely done!. I will go ahead and close this issue.

**Comment by Mimi1510** [comment]
The link below is the wireframe of the animation search not found:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A26051

**Comment by Mimi1510** [comment]
The link below is the lo-fi of the animation search not found:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A24355

**Comment by Mimi1510** [comment]
The link below is the wi-fi of the animation search not found (Authenticated):

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A31083

**Comment by Mimi1510** [comment]
The link below is the hi-fi of the animation search not found (Unauthenticated users):

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A114847

**Comment by Mimi1510** [comment]
The link below is the hi-fi of the animation search not found (Authenticated users):

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2753%3A55293

**Comment by Mimi1510** [comment]
The animation search not found page is designed for both authenticated and unauthenticated users to make the users aware that the particular animations they searched for isn't available.
