### ISSUE TITLE
Design the page that will display "Password change successful"

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#46]

**Comment by jcuchea** [comment]
task completed 
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1696%3A9194

**Comment by jcuchea** [comment]
Rectified as necessary. The new link is attached below.
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2778%3A46840
