### ISSUE TITLE
Design the page that will display "Message sent successfully"

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#47]

**Comment by DuoACe** [comment]
Finally done it

**Comment by DuoACe** [comment]
This is the link to the message successfully sent page
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1701%3A10694

**Comment by DuoACe** [comment]
Kindly check it out
And if you have any issue, kindly reach out to me on slack

**Comment by DuoACe** [comment]
This is the updated link to the Figma link for this task
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A103811
