### ISSUE TITLE
Design the page that will display "Save changes successful"

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#48]

**Comment by Aliyatadeyanju** [comment]
I have started working on it...

**Comment by HamzahOpemipo** [comment]
Hi @Aliyatadeyanju , Please attach the link to the page you worked on when you done then go ahead to close this issue. Weldone!

**Comment by Aliyatadeyanju** [comment]
https://www.figma.com/file/j1drbvRXQLsqEpHG3DfsbP/changes-successfully-saved-page?node-id=0%3A1

**Comment by Aliyatadeyanju** [comment]
Done
