### ISSUE TITLE
Design the page that will display "animation search "

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#49]

**Comment by Mimi1510** [comment]
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2020%3A14969

**Comment by HamzahOpemipo** [comment]
Hi @Mimi1510, Nicely done!. I will go ahead and close this issue

**Comment by Mimi1510** [comment]
The below is the link to the wireframe of the **Animation search page**:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A26110

**Comment by Mimi1510** [comment]
The below is the link to the lo-fi of the **Animation search page (Authenticated users)**:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2922%3A22300

**Comment by Mimi1510** [comment]
The below is the link to the lo-fi of the **Animation search page (Authenticated users)**:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A31098

**Comment by Mimi1510** [comment]
The below is the link to the hi-fi of the **Animation search page (Authenticated users)**:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A115033

**Comment by Mimi1510** [comment]
The below is the link to the hi-fi of the **Animation search page (Unauthenticated users)**:

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2753%3A54907
