### ISSUE TITLE
develop message successful prompt pop up

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#55]

**Comment by DuoACe** [comment]
Kindly work on the light mode first Armstrong
Then we can progress to dark mode later as it'll be a future feature

**Comment by DuoACe** [comment]
Kindly reach out to me on slack for the illustration i used in the page's design

**Comment by DuoACe** [comment]
This is the figma link to the message successfully sent prompt
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=1701%3A10694

**Comment by Armstrong4** [comment]
Message successful prompt pop-up Completed.
