### ISSUE TITLE
Design the page for animation generator page in low fidelity and high fidelity

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#58]

**Comment by OluwakemiOy** [comment]
These are the links to the low fidelity designs for the animation generator page

Animation generator 1
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2584%3A14466

Animations generator 2
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2483%3A19275

**Comment by Oderindecaleb** [comment]
Hi-fi for animator generator
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2808%3A33675

Lo-fi for animation generator
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A21088
