### ISSUE TITLE
Design the page that will allow users reset or change their password

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#64]

**Comment by OsawaruErica** [comment]
link to password recovery page
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2778%3A47198

**Comment by OsawaruErica** [comment]
this page directs users to email where link instruction to change password is given
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2778%3A46917

**Comment by OsawaruErica** [comment]
this page is where the user gets to input new password
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2778%3A46943

**Comment by OsawaruErica** [comment]
email message that will be sent to the user upon clicking on check email for password reset

https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3129%3A19112
