### ISSUE TITLE
Design the page where the users can easily generate their own custom animations

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#66]
Design link for the generation page: 
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A116260

**Comment by OluwakemiOy** [comment]
This is the link for the high fidelity design for the animation generator page 1
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2800%3A30163
