### ISSUE TITLE
Design the interactions for all the pages of the high-fidelity design

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#68]

**Comment by Fawazah** [comment]
We have prototyped the first flow, which is for the unauthenticated users

**Comment by Fawazah** [comment]
Below is the link to our prototype for testing. 
[Prototype of high fidelity design](https://www.figma.com/proto/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?page-id=2712%3A29511&node-id=2712%3A88887&viewport=4453%2C618%2C0.07&scaling=scale-down&starting-point-node-id=2712%3A88887&show-proto-sidebar=1)
It consists of two flows - Unauthenticated user flow and Authenticated user flow

**Comment by Awe80me** [comment]
Thank you Fawzah for the provided link.
