### ISSUE TITLE
Conduct user research to aid the development of the product

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#83]

**Comment by OsawaruErica** [comment]
Organized notes gathered from the research carried out
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47586

Empathy map worked on to help understand the user
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47589

Pain points of the user
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47592

User story
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A62896

**Comment by Awe80me** [comment]
Worked on the user story to help better understand the user and come up with design solutions for the user;
[User Story](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A62896)

Worked on the user persona which brought the team closer to our user;
[User Persona](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2880%3A29147)

**Comment by Fawazah** [comment]
Issues where discovered while designing, so we had to iterate and conduct more research to better empathize with users. Which allowed us to discover more pain points and come up with better ideas to solve these pain points.

Worked on a user story to understand the persona's point of view, to inspire and inform our design decisions;
[User Story 2](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A62925)
