### ISSUE TITLE
Construct overall site map for the product

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#85]

**Comment by Oderindecaleb** [comment]
link to finished site map - https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47580

**Comment by Awe80me** [comment]
Below is the link to the overall sitemap of the product;

[Site Map](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47580)

**Comment by OsawaruErica** [comment]
Site map for the product completed
https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47580

**Comment by Fawazah** [comment]
Changes where made to the site map while designing has we discovered flaws in our initial site map.

**Comment by DuoACe** [comment]
The site map looks good and it's ready to go. Well done to all of us
