### ISSUE TITLE
Edoghogho Erica Osawaru Individual contribution

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#87]

**Comment by OsawaruErica** [comment]
**Tasks assigned to me with links to resolved issues I proffered solutions to** 


1. [Link for resolved input fields I worked on in style guide](https://github.com/zuri-training/Team-100_AnimaLib/issues/25#issuecomment-1209609108)

2. [Link for resolved Issue for Animo logo designed for the animation library](https://github.com/zuri-training/Team-100_AnimaLib/issues/72)
 
3. [Link for resolved Issue for the various pages that allows the user to reset password](https://github.com/zuri-training/Team-100_AnimaLib/issues/64)

4. [Link to resolved issue for error 500 page design](https://github.com/zuri-training/Team-100_AnimaLib/issues/44)

5. [Link for resolved issue for project documentation worked on](https://github.com/zuri-training/Team-100_AnimaLib/issues/29#issuecomment-1209329245)

6. [Link to the resolved issue for user research plan document](https://github.com/zuri-training/Team-100_AnimaLib/issues/27#issuecomment-1209323493)

7. [Link to resolved issue for low fidelity design of register/login page](https://github.com/zuri-training/Team-100_AnimaLib/issues/22)

8. [Link to resolved issue for high fidelity design of register/login page](https://github.com/zuri-training/Team-100_AnimaLib/issues/21)

9. [Link to resolved issue for user research empathy map and organized notes worked on](https://github.com/zuri-training/Team-100_AnimaLib/issues/83#issuecomment-1210331613)

10. [Link to resolved issues for site map](https://github.com/zuri-training/Team-100_AnimaLib/issues/85)
