### ISSUE TITLE
Joseph-Uchea Jordan II Individual contribution

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#88]

**Comment by jcuchea** [comment]
### During the course of this project phase, I was assigned the following tasks :
1. [**Design the page that will display "Password change successful" #46**](uhttps://github.com/zuri-training/Team-100_AnimaLib/issues/46rl)
2. [**Design a Register/Log in page #21**](uhttps://github.com/zuri-training/Team-100_AnimaLib/issues/21rl)
3. [**Design a Register/Sign page in low fidelity #22** ](urlhttps://github.com/zuri-training/Team-100_AnimaLib/issues/22)
4. [**Brainstorm on ideas #16**](uhttps://github.com/zuri-training/Team-100_AnimaLib/issues/16rl)


### Here are the solutions to my assigned tasks:
1. [For the Lo-Fi of the Password successfully changed screen](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A17219)
2. [For the Hi-Fi of the Password successfully changed" screen](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2778%3A46840)
3. [The Brainstorming Idea matrix](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47674)
4. [The Brainstormed Ideas](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2880%3A27332)
5. [ The Lo-Fi of the Login and Sign up page ](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A17634)
6. [The Hi-Fi of the Login and sign up page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2778%3A46895)
