### ISSUE TITLE
Uthman Akinsawe Individual contribution

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#91]

**Comment by Awe80me** [comment]
### ISSUES I DIRECTLY WORKED ON AND THE SOLUTIONS I CAME UP WITH

**Issue link**: #83 

**Solution links;** 
[User Story](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A62896)
[User Persona](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2880%3A29147)
