### ISSUE TITLE
Hamzah Opemipo Individual Submission

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#94]

**Comment by HamzahOpemipo** [comment]
During the course of this project phase, I was assigned the following tasks :
1. Brainstorm on ideas #16 
2. Design several wireframe for the user profile pages #26 
3. Design several low fidelity for the user profile pages #39 
4. Produce high fidelity designs of the user profile pages  #40 

Solutions to the tasks I was assigned to : 
1. During the brainstorming session, I drew a [Rough user flow sletch](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3593%3A19426) which was a guide in designing the [User flow](: https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A63197)
2. Designed wireframes for the User profile section. This section consists of the following pages :  Profile Dropdown [Profile dropdown](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25008) , [Profile page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25098) , [View profile page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25041) , [Edit profile page](: https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25176) , [Edit Profile (Expanded)](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25208) and [My saves page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25238)
3. Went ahead to turn all the pages created in the wireframe to [Low Fidelity Designs](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3585%3A19428)
4. Then designed the [High fidelity designs](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3585%3A19426).

**Comment by HamzahOpemipo** [comment]
During the course of this project phase, I was assigned the following tasks :

Brainstorm on ideas https://github.com/zuri-training/Team-100_AnimaLib/issues/16
Design several wireframe for the user profile pages https://github.com/zuri-training/Team-100_AnimaLib/issues/26
Design several low fidelity for the user profile pages Design several pages for User profile in low fidelity  #39
Produce high fidelity designs of the user profile pages Design several pages for User profile in high fidelity  #40
Solutions to the tasks I was assigned to :

During the brainstorming session, I drew a [Rough user flow sletch](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3593%3A19426) which was a guide in designing the [User flow](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2712%3A63197)
Designed wireframes for the User profile section. This section consists of the following pages : Profile Dropdown [Profile dropdown](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25008) , [Profile page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25098) , [View profile page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25041) , [Edit profile page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25176) , [Edit Profile (Expanded)](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25208) and [My saves page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2882%3A25238)
Went ahead to turn all the pages created in the wireframe to [Low Fidelity Designs](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3585%3A19428)
Then designed the [High fidelity designs](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3585%3A19426).
